# Generated by Django 5.2.1 on 2025-05-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_taskresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(default='Общая', max_length=100, verbose_name='Предметная область'),
            preserve_default=False,
        ),
    ]
